# Generated by Django 4.0.4 on 2022-05-13 15:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('height', models.CharField(max_length=5)),
                ('weight', models.CharField(max_length=5)),
                ('team', models.CharField(max_length=120)),
                ('noc', models.CharField(max_length=3)),
                ('sex', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('season', models.CharField(choices=[('Summer', 'Summer'), ('Winter', 'Winter')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('sport', models.CharField(max_length=255)),
                ('games', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympic.games')),
            ],
        ),
        migrations.CreateModel(
            name='AthleteEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medal', models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronze', 'Bronze'), ('NA', 'NA')], max_length=6)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympic.athlete')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympic.event')),
                ('games', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympic.games')),
            ],
        ),
    ]
