# Generated by Django 4.0.4 on 2022-05-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0002_games_games_alter_athlete_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='athlete_id',
            field=models.CharField(default='0000000', max_length=255),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
