# Generated by Django 4.0.4 on 2022-05-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0003_athlete_athlete_id_alter_athlete_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='age',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
